### ISSUE TITLE
crash when running script

### ISSUE THREAD

**Issue by praetp** [memosstilvi/emr-cost-calculator#5]
./emr_cost_calculator.py cluster --region=eu-west-1 --cluster_id=j-GCYS9FTHGE3I
[INFO] Retrieving cost in region eu-west-1
Traceback (most recent call last):
  File "./emr_cost_calculator.py", line 266, in <module>
    print calc.get_cluster_cost(args.get('--cluster_id'))
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "./emr_cost_calculator.py", line 145, in get_cluster_cost
    instance_groups = self._get_instance_groups(cluster_id)
  File "./emr_cost_calculator.py", line 203, in _get_instance_groups
    inst_group.price = prices[group.instancetype]['ec2'] + \
KeyError: u'm4.xlarge'

**Comment by memosstilvi** [comment]
@spetsnaz84 sorry for the late response.
I believe this is happening becuase `m4.xlarge` is missing from the [config.yml file](https://github.com/memosstilvi/emr-cost-calculator/blob/master/config.yml)
